# generated by picking two numbers between 1 and 20
# return formatted question
# no need to store list of questions permanently, 
# because they're not needed once the user has seen/answered them

class Question




end